### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by padoru233** [ikaros-dev/plugin-mikan#1]
ikaros为最新版本
Dependencies '[WrongDependencyVersion{dependencyId='PluginBgmTv', dependentId='PluginMikan', existingVersion='0.11.9', requiredVersion='0.11.0'}]' have wrong version

**Comment by chivehao** [comment]
额，这个仓库我好像没收到邮件，抱歉回复晚了，这个插件好像目前还没适配最新版本

**Comment by chivehao** [comment]
个人不建议使用。这个插件实在是有点难用，
主要问题还是在和第三方`Qbittorrent`交互上，这里涉及的用户容器权限问题比较复杂，
可能等未来 `ikaros` 通过插件实现了 BT下载，这个插件用起来才比较方便。
暂时个人推进这个插件的开发进度意愿不大，不过我会尽快适配下 本体 0.11 版本

**Comment by chivehao** [comment]
已经适配最新版：

- https://github.com/ikaros-dev/plugin-mikan/releases/tag/v0.11.7
