### ISSUE TITLE
上传插件报错

### ISSUE THREAD

**Issue by cosmos0715** [ikaros-dev/plugin-mikan#2]
Plugin '/root/.ikaros/plugins/plugin-mikan-0.11.0.jar' already loaded with id 'PluginMikan'
![Uploading 屏幕截图 2023-12-13 195149.jpg…]()

**Comment by chivehao** [comment]
额，这个仓库我好像没收到邮件，抱歉回复晚了，和下面这个issue重复
- https://github.com/ikaros-dev/plugin-mikan/issues/1
